---

static_targets:
-
     target_name: modified_circle_4x3
     target_type: 2
     circle_dia:  0.0254
     spacing:  0.03556
     target_frame: target
     transform_interface: ros_scti
     parent_frame: world
     target_rows: 4
     target_cols: 3

