camera_color_optical_frame_pitch_joint: 0.0
camera_color_optical_frame_roll_joint: 0.0
camera_color_optical_frame_x_joint: 0.0
camera_color_optical_frame_y_joint: 0.0
camera_color_optical_frame_yaw_joint: 0.0
camera_color_optical_frame_z_joint: 0.0
target_pitch_joint: -0.02
target_roll_joint: -0.5421
target_x_joint: 0.7158
target_y_joint: 0.2581
target_yaw_joint: -0.17
target_z_joint: 0.5063
