---

static_cameras:
 -
    camera_name: camera/color
    camera_optical_frame: realsense_optical_frame
    trigger: NO_WAIT_TRIGGER
    image_directory: /tmp/images
    transform_interface: ros_camera_housing_cti
    camera_housing_frame: realsense
    camera_mounting_frame: tool0
    image_topic: /camera/color/image_raw
    image_width: 640
    image_height: 480

